import nodemailer from "nodemailer";

const transporter = nodemailer.createTransport({
    service: import.meta.env.VITE_EMAIL_SERVICE,
    auth: {
        user: import.meta.env.VITE_EMAIL_USER,
        pass: import.meta.env.VITE_EMAIL_PASS
    }
});

export async function sendEmail(to: string, subject: string, text: string) {
  try {
    const info = await transporter.sendMail({
      from: 'Astro Dates',
      to,
      subject,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h1 style="color: #333;">Your Zodiac Sign Comparison</h1>
          <div style="line-height: 1.6;">
            ${text}
          </div>
          <p style="color: #666; font-size: 0.9em; margin-top: 20px;">
            Generated by Your Zodiac App
          </p>
        </div>
      `,
    });
    console.log("Email sent: %s", info.messageId);
    return { success: true, messageId: info.messageId };

  } catch (error) {
    console.error("Error sending email:", error);
    return { success: false, error };
  }
}
